import {
  Region,
  Zone,
  LiteratureItem,
  ArchiveItem,
  ManuscriptItem,
  Submission,
  Assessment,
  CollectionRecord,
  DashboardStats,
} from '../types';

export const SAMPLE_REGIONS: Region[] = [
  {
    id: 'reg-amhara',
    name: 'Amhara',
    amharicName: 'አማራ',
    code: 'AMH',
    capital: 'Bahir Dar',
    description: 'Home to Lake Tana island monasteries, Lalibela rock-hewn churches, and the imperial castles of Gondar, holding centuries of Ge\'ez illuminated manuscripts.',
    zonesCount: 11,
    recordsCount: 428,
  },
  {
    id: 'reg-tigray',
    name: 'Tigray',
    amharicName: 'ትግራይ',
    code: 'TIG',
    capital: 'Mekelle',
    description: 'Cradle of ancient Aksumite civilization and home to the Abba Garima Gospels, Debre Damo monastery, and early Christian and Islamic historical sites.',
    zonesCount: 7,
    recordsCount: 392,
  },
  {
    id: 'reg-oromia',
    name: 'Oromia',
    amharicName: 'ኦሮሚያ',
    code: 'ORO',
    capital: 'Addis Ababa / Finfinnee',
    description: 'Rich in Gadaa system administrative archives, oral literature transcriptions, Afaan Oromoo codices, and Sheikh Hussein historical documents.',
    zonesCount: 21,
    recordsCount: 345,
  },
  {
    id: 'reg-harari',
    name: 'Harari',
    amharicName: 'ሐረሪ',
    code: 'HAR',
    capital: 'Harar',
    description: 'The historic fortified historic town of Harar Jugol, renowned for rare Arabic and Harari Ajami manuscripts, Islamic jurisprudence archives, and calligraphy.',
    zonesCount: 3,
    recordsCount: 215,
  },
  {
    id: 'reg-addis-ababa',
    name: 'Addis Ababa',
    amharicName: 'አዲስ አበባ',
    code: 'ADD',
    capital: 'Addis Ababa',
    description: 'National Archives and Library of Ethiopia (Wemezekr), Institute of Ethiopian Studies, and national royal archives.',
    zonesCount: 10,
    recordsCount: 760,
  },
  {
    id: 'reg-afar',
    name: 'Afar',
    amharicName: 'ዓፋር',
    code: 'AFR',
    capital: 'Semera',
    description: 'Traditional Sultanate diplomatic archives, pastoralist customary law documentations, and historical trade route scrolls.',
    zonesCount: 5,
    recordsCount: 94,
  },
  {
    id: 'reg-somali',
    name: 'Somali',
    amharicName: 'ሶማሌ',
    code: 'SOM',
    capital: 'Jijiga',
    description: 'Rich traditions of classical poetry archives, Islamic theological commentaries, and regional treaty documents.',
    zonesCount: 9,
    recordsCount: 132,
  },
  {
    id: 'reg-sidama',
    name: 'Sidama',
    amharicName: 'ሲዳማ',
    code: 'SID',
    capital: 'Hawassa',
    description: 'Luwa customary system documents, Fichee-Chambalaalla heritage archives, and Southern Rift Valley cultural documentation.',
    zonesCount: 4,
    recordsCount: 110,
  },
];

export const SAMPLE_ZONES: Zone[] = [
  {
    id: 'zone-north-gondar',
    name: 'North Gondar',
    amharicName: 'ሰሜን ጎንደር',
    code: 'AMH-NGD',
    regionId: 'reg-amhara',
    regionName: 'Amhara',
    description: 'Imperial records of Fasil Ghebbi, Debre Berhan Selassie murals documentation, and parchment archives.',
    recordsCount: 142,
  },
  {
    id: 'zone-lasta',
    name: 'North Wollo / Lalibela (Lasta)',
    amharicName: 'ሰሜን ወሎ / ላሊበላ',
    code: 'AMH-NWL',
    regionId: 'reg-amhara',
    regionName: 'Amhara',
    description: 'Zagwe dynasty liturgical scrolls, ancient parchment psalters, and rock church endowments.',
    recordsCount: 168,
  },
  {
    id: 'zone-axum',
    name: 'Central Tigray / Axum',
    amharicName: 'ማዕከላዊ ትግራይ / አክሱም',
    code: 'TIG-AXM',
    regionId: 'reg-tigray',
    regionName: 'Tigray',
    description: 'Aksum Tsion parchment codices, Garima monastery archives, and royal Sabaean epigraphy.',
    recordsCount: 198,
  },
  {
    id: 'zone-harar-jugol',
    name: 'Harar Jugol Historical Zone',
    amharicName: 'የሐረር ጁጎል ታሪካዊ ዞን',
    code: 'HAR-JUG',
    regionId: 'reg-harari',
    regionName: 'Harari',
    description: 'Walled town archival registry, handwritten Quranic illuminated codices, and Amirate decrees.',
    recordsCount: 180,
  },
  {
    id: 'zone-arada',
    name: 'Arada Sub-City (Wemezekr Central)',
    amharicName: 'አራዳ ክፍለ ከተማ',
    code: 'ADD-ARD',
    regionId: 'reg-addis-ababa',
    regionName: 'Addis Ababa',
    description: 'National Archives depository, original treaty holdings, and national rare book repository.',
    recordsCount: 420,
  },
  {
    id: 'zone-jimma',
    name: 'Jimma Zone',
    amharicName: 'ጅማ ዞን',
    code: 'ORO-JMA',
    regionId: 'reg-oromia',
    regionName: 'Oromia',
    description: 'Kingdom of Jimma Abba Jifar royal correspondence, commercial trade route archives, and Oromo oral law transcription.',
    recordsCount: 124,
  },
];

export const SAMPLE_MANUSCRIPTS: ManuscriptItem[] = [
  {
    id: 'ms-garima-1',
    title: 'The Abba Garima Gospels (Codex Garima I)',
    author: 'Monastic Scribes of Saint Garima',
    estimatedDate: 'c. 390 – 650 CE (Late Antiquity)',
    language: 'Ge\'ez (Ancient Ethiopic)',
    script: 'Unvocalized & Early Vocalized Ethiopic Script',
    description: 'One of the earliest surviving illustrated Christian codices in the entire world, preserved for over 1,500 years atop the cliffs of Garima Monastery. The parchment is written on premium goat vellum with natural mineral pigments.',
    historicalSignificance: 'Monumental global testimony to early Christian art, manuscript transmission in the Horn of Africa, and indigenous leather craftsmanship.',
    physicalCondition: 'Fragile',
    currentLocation: 'Abba Garima Monastery Treasury, Adwa, Tigray',
    regionId: 'reg-tigray',
    zoneId: 'zone-axum',
    regionName: 'Tigray',
    zoneName: 'Central Tigray / Axum',
    status: 'ARCHIVED',
    foliopages: 348,
    fileName: 'abba_garima_codex_i_master_digitization.pdf',
    fileSize: '18.4 MB',
    fileUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2025-01-14T09:30:00Z',
  },
  {
    id: 'ms-kebra-nagast',
    title: 'Kebra Nagast (The Glory of the Kings)',
    author: 'Nebura\'ed Yeshaq of Aksum (Compiler/Scribe)',
    estimatedDate: 'c. 1320 CE (Solomonic Dynasty Era)',
    language: 'Ge\'ez',
    script: 'Classic Classical Ethiopic Calligraphy',
    description: 'The national epic detailing the lineage of King Solomon and the Queen of Sheba (Makeda), the birth of Menelik I, and the translation of the Ark of the Covenant to Aksum. Written with vibrant black carbon and vermilion red rubrications.',
    historicalSignificance: 'Formative cultural and constitutional foundational text of traditional Ethiopian statecraft and national identity.',
    physicalCondition: 'Good',
    currentLocation: 'National Archives & Library of Ethiopia (Wemezekr Collection), Addis Ababa',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'APPROVED',
    foliopages: 216,
    fileName: 'kebra_nagast_parchment_scan_1320.pdf',
    fileSize: '14.2 MB',
    fileUrl: 'https://images.unsplash.com/photo-1532012164546-f432f2e3777f?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2025-02-02T11:15:00Z',
  },
  {
    id: 'ms-henok-1',
    title: 'Metsehafe Henok (The Book of 1 Enoch)',
    author: 'Traditional Monastery Scribe School of Gunda Gunde',
    estimatedDate: 'c. 1450 CE',
    language: 'Ge\'ez',
    script: 'Goffar-style Monumental Ge\'ez',
    description: 'The only complete surviving ancient version of the Book of Enoch anywhere on earth exists exclusively in Ge\'ez. This illuminated codex includes astronomical calculations, angelic visions, and apocalyptic wisdom.',
    historicalSignificance: 'Unique worldwide preservation of second-temple apocalyptic literature lost in Greek and Aramaic originals.',
    physicalCondition: 'Pristine',
    currentLocation: 'Institute of Ethiopian Studies, Addis Ababa University',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'ARCHIVED',
    foliopages: 180,
    fileName: 'metsehafe_henok_gunda_gunde.pdf',
    fileSize: '12.8 MB',
    fileUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2025-02-18T14:45:00Z',
  },
  {
    id: 'ms-harar-quran',
    title: 'The Great Illuminated Harari Quran',
    author: 'Calligrapher Sheikh Abdurrahman al-Harari',
    estimatedDate: 'c. 1680 CE',
    language: 'Arabic with Harari Ajami glosses',
    script: 'Maghrebi-influenced Horn of Africa Calligraphy with Gold Leaf',
    description: 'A masterwork of Harari Islamic calligraphy featuring intricate geometric frontispieces, floral illumination in lapis lazuli and vermilion ink, and marginal notes explaining local jurisprudence.',
    historicalSignificance: 'Highlights Harar\'s pivotal role as the fourth holiest city of Islam and an epicenter of manuscript artistry in the Horn.',
    physicalCondition: 'Good',
    currentLocation: 'Sherif Harar City Museum Manuscript Vault',
    regionId: 'reg-harari',
    zoneId: 'zone-harar-jugol',
    regionName: 'Harari',
    zoneName: 'Harar Jugol Historical Zone',
    status: 'APPROVED',
    foliopages: 412,
    fileName: 'harari_illuminated_quran_1680.pdf',
    fileSize: '19.6 MB',
    fileUrl: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2025-03-01T10:00:00Z',
  },
  {
    id: 'ms-taamra-maryam',
    title: 'Ta\'amra Maryam (Miracles of Mary illuminated codex)',
    author: 'Royal Scriptorium of Emperor Dawit I',
    estimatedDate: 'c. 1395 – 1410 CE',
    language: 'Ge\'ez',
    script: 'Rubricated Liturgical Calligraphy',
    description: 'Lavishly illuminated parchment containing 74 full-page miniatures depicting holy narratives, royal patrons, and floral Ge\'ez knotwork (harag) dividers.',
    historicalSignificance: 'Prime artifact illustrating the zenith of 15th-century Ethiopian Christian miniature painting and royal patronage.',
    physicalCondition: 'Fragile',
    currentLocation: 'Daga Estifanos Monastery, Lake Tana',
    regionId: 'reg-amhara',
    zoneId: 'zone-north-gondar',
    regionName: 'Amhara',
    zoneName: 'North Gondar',
    status: 'COLLECTED',
    foliopages: 290,
    fileName: 'taamra_maryam_daga_estifanos.pdf',
    fileSize: '16.5 MB',
    createdAt: '2025-03-04T08:20:00Z',
  },
];

export const SAMPLE_LITERATURE: LiteratureItem[] = [
  {
    id: 'lit-fikir-eske-meqabir',
    title: 'Fikir Eske Meqabir (Love unto the Grave)',
    author: 'Haddis Alemayehu',
    language: 'Amharic',
    publicationYear: 1968,
    category: 'Historical Fiction / Classic Novel',
    description: 'Regarded as the pinnacle of 20th-century Amharic literature. It chronicles the tragic romance of Bezabih and Seblewongel while delivering an astute sociological analysis of late feudal Ethiopian nobility.',
    location: 'National Library of Ethiopia, Section LIT-ETH-68',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'APPROVED',
    createdAt: '2025-01-10T12:00:00Z',
  },
  {
    id: 'lit-tobbya',
    title: 'Tobbya (Lebb Wallad Tarik)',
    author: 'Afework Gebre Yesus',
    language: 'Amharic',
    publicationYear: 1908,
    category: 'Pioneering Novel / Allegory',
    description: 'Published in Rome in 1908, Tobbya is widely celebrated as the first modern novel written in the Amharic language and printed in Ethiopic typeface.',
    location: 'Institute of Ethiopian Studies Rare Books',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'ARCHIVED',
    createdAt: '2025-01-15T15:30:00Z',
  },
  {
    id: 'lit-oromoo-history',
    title: 'Seenaa Oromoo (Historical Chronicles & Gadaa Oral Records)',
    author: 'Oral Historians Assembly (Recorded by Oromia Heritage Institute)',
    language: 'Afaan Oromoo',
    publicationYear: 1974,
    category: 'Indigenous Governance / History',
    description: 'Comprehensive ethnographic records documenting the 8-year generational cycles of the democratic Gadaa governance system, laws of Chaffee assemblies, and regional chronicles.',
    location: 'Jimma University Cultural Archives Center',
    regionId: 'reg-oromia',
    zoneId: 'zone-jimma',
    regionName: 'Oromia',
    zoneName: 'Jimma Zone',
    status: 'APPROVED',
    createdAt: '2025-02-12T10:00:00Z',
  },
  {
    id: 'lit-ke-admas-bashager',
    title: 'Ke Admas Bashager (Beyond the Horizon)',
    author: 'Baalu Girma',
    language: 'Amharic',
    publicationYear: 1970,
    category: 'Philosophical Realism',
    description: 'A seminal work of social critique examining modern urbanization, intellectual alienation, and youthful idealism in mid-twentieth century Addis Ababa.',
    location: 'Wemezekr Public Circulation Branch',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'APPROVED',
    createdAt: '2025-02-20T16:10:00Z',
  },
  {
    id: 'lit-zara-yaqob-hatata',
    title: 'Hatata (Inquiry of Zera Yacob)',
    author: 'Zera Yacob (Philosopher of Axum)',
    language: 'Ge\'ez',
    publicationYear: 1667,
    category: 'Enlightenment Philosophy / Rationalism',
    description: 'A seventeenth-century rationalist treatise composed in a cave near the Tekeze River. Zera Yacob applied independent rational inquiry to ethics, religion, and human reason contemporaneous with René Descartes.',
    location: 'Aksum Archaeological Museum Reading Hall',
    regionId: 'reg-tigray',
    zoneId: 'zone-axum',
    regionName: 'Tigray',
    zoneName: 'Central Tigray / Axum',
    status: 'ARCHIVED',
    createdAt: '2025-02-28T14:00:00Z',
  },
];

export const SAMPLE_ARCHIVES: ArchiveItem[] = [
  {
    id: 'arc-wuchale-1889',
    title: 'Treaty of Wuchale (Original Amharic & Italian Imperial Accord)',
    archiveType: 'Diplomatic Treaty / State Accord',
    description: 'The historic May 2, 1889 accord between Emperor Menelik II and King Umberto I. The famous discrepancy in Article XVII led to the historic Battle of Adwa in 1896, preserving Ethiopia\'s uncolonized sovereignty.',
    date: 'May 2, 1889',
    language: 'Amharic & Italian',
    location: 'Wemezekr National Archives Special Vault A-1',
    documentNumber: 'ARC-ETH-DIP-1889-001',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'ARCHIVED',
    createdAt: '2025-01-08T10:00:00Z',
  },
  {
    id: 'arc-adwa-dispatches',
    title: 'Battle of Adwa Imperial Military Field Orders and Telegraph Dispatches',
    archiveType: 'Military Command / Imperial Decrees',
    description: 'Original seals and parchment orders of Emperor Menelik II, Empress Taytu Betul, and Ras Alula Engida during the mobilization and victory at Adwa in March 1896.',
    date: 'March 1, 1896',
    language: 'Amharic',
    location: 'National Military Museum Archival Registry',
    documentNumber: 'ARC-ADW-1896-ORD-04',
    regionId: 'reg-tigray',
    zoneId: 'zone-axum',
    regionName: 'Tigray',
    zoneName: 'Central Tigray / Axum',
    status: 'APPROVED',
    createdAt: '2025-01-20T11:45:00Z',
  },
  {
    id: 'arc-harar-customs',
    title: 'Harar Jugol Royal Amirate Commercial Tax Register',
    archiveType: 'Trade Registry / Customary Ledger',
    description: 'Detailed ledgers of the Amir of Harar recording caravans arriving from Zeila and Berbera, listing spices, coffee, textiles, and ivory tariffs.',
    date: '1854 CE',
    language: 'Arabic',
    location: 'Harar Historical Archive Center',
    documentNumber: 'ARC-HAR-1854-CUS',
    regionId: 'reg-harari',
    zoneId: 'zone-harar-jugol',
    regionName: 'Harari',
    zoneName: 'Harar Jugol Historical Zone',
    status: 'COLLECTED',
    createdAt: '2025-02-14T09:15:00Z',
  },
  {
    id: 'arc-league-nations-1935',
    title: 'Appeal to the League of Nations Official Memorandum & Telegrams',
    archiveType: 'International Diplomatic Registry',
    description: 'Certified diplomatic copies of Emperor Haile Selassie I\'s 1935 telegraphic protests and 1936 speech at Geneva denouncing chemical gas warfare and foreign aggression.',
    date: 'June 30, 1936',
    language: 'Amharic & French',
    location: 'National Archives Vault B-4',
    documentNumber: 'ARC-LN-1936-GENEVA',
    regionId: 'reg-addis-ababa',
    zoneId: 'zone-arada',
    regionName: 'Addis Ababa',
    zoneName: 'Arada Sub-City (Wemezekr Central)',
    status: 'ARCHIVED',
    createdAt: '2025-02-25T13:20:00Z',
  },
];

export const SAMPLE_SUBMISSIONS: Submission[] = [
  {
    id: 'sub-001',
    title: 'The Abba Garima Gospels (Codex Garima I)',
    itemType: 'MANUSCRIPT',
    itemId: 'ms-garima-1',
    submitterId: 'usr-zone-01',
    submitterName: 'Teklehaimanot Gebremariam',
    submitterEmail: 't.gebremariam@tigray.heritage.et',
    status: 'ARCHIVED',
    submittedAt: '2025-01-14T09:30:00Z',
    notes: 'Digitized with multi-spectral photography on site with monastic custodial consent.',
    regionId: 'reg-tigray',
    zoneId: 'zone-axum',
    regionName: 'Tigray',
    zoneName: 'Central Tigray / Axum',
  },
  {
    id: 'sub-002',
    title: 'Ta\'amra Maryam (Miracles of Mary illuminated codex)',
    itemType: 'MANUSCRIPT',
    itemId: 'ms-taamra-maryam',
    submitterId: 'usr-zone-02',
    submitterName: 'Merigeta Fikru Kassaye',
    submitterEmail: 'f.kassaye@amhara.heritage.et',
    status: 'COLLECTED',
    submittedAt: '2025-03-04T08:20:00Z',
    notes: 'Physical collection completed by regional conservators; pending permanent dehumidified archiving.',
    regionId: 'reg-amhara',
    zoneId: 'zone-north-gondar',
    regionName: 'Amhara',
    zoneName: 'North Gondar',
  },
  {
    id: 'sub-003',
    title: 'Harar Jugol Royal Amirate Commercial Tax Register',
    itemType: 'ARCHIVE',
    itemId: 'arc-harar-customs',
    submitterId: 'usr-zone-03',
    submitterName: 'Amina Sharif',
    submitterEmail: 'amina.sharif@harar.gov.et',
    status: 'APPROVED',
    submittedAt: '2025-02-14T09:15:00Z',
    notes: 'Reviewed by National Manuscript Commission; passed paleographic authenticity screening.',
    regionId: 'reg-harari',
    zoneId: 'zone-harar-jugol',
    regionName: 'Harari',
    zoneName: 'Harar Jugol Historical Zone',
  },
  {
    id: 'sub-004',
    title: 'Seenaa Oromoo (Historical Chronicles & Gadaa Oral Records)',
    itemType: 'LITERATURE',
    itemId: 'lit-oromoo-history',
    submitterId: 'usr-zone-04',
    submitterName: 'Dr. Gemechu Megersa',
    submitterEmail: 'gemechu.m@oromia.heritage.et',
    status: 'UNDER_REVIEW',
    submittedAt: '2025-03-08T14:30:00Z',
    notes: 'Awaiting secondary linguistic verification of archaic Oromo idioms.',
    regionId: 'reg-oromia',
    zoneId: 'zone-jimma',
    regionName: 'Oromia',
    zoneName: 'Jimma Zone',
  },
  {
    id: 'sub-005',
    title: 'Zoba Enderta 18th Century Ecclesiastical Land Endowments',
    itemType: 'ARCHIVE',
    submitterId: 'usr-zone-01',
    submitterName: 'Teklehaimanot Gebremariam',
    submitterEmail: 't.gebremariam@tigray.heritage.et',
    status: 'SUBMITTED',
    submittedAt: '2025-03-09T16:00:00Z',
    notes: 'New submission from Mekelle University archives team.',
    regionId: 'reg-tigray',
    zoneId: 'zone-axum',
    regionName: 'Tigray',
    zoneName: 'Central Tigray / Axum',
  },
];

export const SAMPLE_ASSESSMENTS: Assessment[] = [
  {
    id: 'ass-001',
    submissionId: 'sub-001',
    submissionTitle: 'The Abba Garima Gospels (Codex Garima I)',
    reviewerId: 'usr-admin-01',
    reviewerName: 'Prof. Tadesse Tamrat',
    decision: 'APPROVED',
    score: 98,
    comments: 'Superlative historical provenance. Radiocarbon dating confirmed antiquity. Multi-spectral digital images fulfill National Heritage preservation standards.',
    createdAt: '2025-01-16T10:00:00Z',
  },
  {
    id: 'ass-002',
    submissionId: 'sub-003',
    submissionTitle: 'Harar Jugol Royal Amirate Commercial Tax Register',
    reviewerId: 'usr-admin-02',
    reviewerName: 'Dr. Rita Pankhurst Archive Fellow',
    decision: 'APPROVED',
    score: 92,
    comments: 'Authentic 19th-century watermarked rag paper and typical Harari scribal colophons verified. Approved for collection.',
    createdAt: '2025-02-18T15:30:00Z',
  },
];

export const SAMPLE_COLLECTIONS: CollectionRecord[] = [
  {
    id: 'col-001',
    submissionId: 'sub-001',
    submissionTitle: 'The Abba Garima Gospels (Codex Garima I)',
    itemType: 'MANUSCRIPT',
    collectorId: 'usr-admin-01',
    collectorName: 'Wemezekr National Conservator Team',
    collectionDate: '2025-01-20',
    collectionLocation: 'On-site Adwa Monastic Conservation Enclosure',
    notes: 'Preserved in specialized inert nitrogen-sealed display case on-site in monastic custody.',
    status: 'ARCHIVED',
    createdAt: '2025-01-20T14:00:00Z',
  },
  {
    id: 'col-002',
    submissionId: 'sub-002',
    submissionTitle: 'Ta\'amra Maryam (Miracles of Mary illuminated codex)',
    itemType: 'MANUSCRIPT',
    collectorId: 'usr-col-01',
    collectorName: 'Amhara Regional Preservation Unit',
    collectionDate: '2025-03-06',
    collectionLocation: 'Bahir Dar Heritage Vault',
    notes: 'Parchment relaxation and binding consolidation currently underway in laboratory.',
    status: 'COLLECTED',
    createdAt: '2025-03-06T11:00:00Z',
  },
];

export const SAMPLE_DASHBOARD_STATS: DashboardStats = {
  totalUsers: 148,
  totalRegions: 12,
  totalZones: 78,
  totalLiterature: 1240,
  totalArchives: 3820,
  totalManuscripts: 2450,
  totalSubmissions: 412,
  pendingSubmissions: 38,
  approvedSubmissions: 312,
  collectedSubmissions: 240,
  recentActivity: [
    {
      id: 'act-1',
      action: 'Manuscript Digitization Approved',
      itemTitle: 'The Abba Garima Gospels (Codex Garima I)',
      user: 'Prof. Tadesse Tamrat',
      timestamp: '2 hours ago',
      status: 'ARCHIVED',
    },
    {
      id: 'act-2',
      action: 'New Literature Registered',
      itemTitle: 'Fikir Eske Meqabir Rare First Edition',
      user: 'Teklehaimanot G.',
      timestamp: '5 hours ago',
      status: 'APPROVED',
    },
    {
      id: 'act-3',
      action: 'Archive Ledger Collected',
      itemTitle: 'Harar Jugol Royal Amirate Commercial Tax Register',
      user: 'Amina Sharif',
      timestamp: '1 day ago',
      status: 'COLLECTED',
    },
    {
      id: 'act-4',
      action: 'New Heritage Submission',
      itemTitle: 'Zoba Enderta Ecclesiastical Land Records',
      user: 'Teklehaimanot G.',
      timestamp: '1 day ago',
      status: 'SUBMITTED',
    },
  ],
};
